### PR TITLE
[JBEE-258] FactoryFinderCache does not properly handle comments in service

### PR DESCRIPTION
**Pull request by TomasHofman**
Issue: https://issues.redhat.com/browse/JBEE-258
Upstream PR: https://github.com/jboss/jboss-jakarta-el-api_spec/pull/6

### CODE REVIEW

**Comment by bstansberry** [comment]
I think we should hold on merging this until we get the 4.0.x fix into WF and get some CI and TCK experience with it. ServiceLoader.load is a lot more complex than just a class.getResourceAsStream(META-INF/services/xxxx), which is good in terms of fixing the bug but is something we should validate in WF main for a bit before backporting.

**Comment by TomasHofman** [comment]
@bstansberry as you mention differences between `class.getResourceAsStream(META-INF/services/xxxx)` and `ServiceLoader.load()`, I noticed one problem it introduces into testing.

This PR contains a test case which I've been unable to port to the 4.0.x branch due to the fact that the 4.0.x branch contains `module-info.java` file (making it a JPMS named module). In that environment, `ServiceLoader.load()` refuses to load my sample service class unless the service interface is listed in the `module-info.java`. I tried to add separate `module-info.java` to test resources dir, that would be used for tests instead of the real one, but I can't make that work.

So now I think if it wouldn't be better to keep using the original `class.getResourceAsStream(META-INF/services/xxxx)` way, and just sanitize what is read from the file.

WDYT @aogburn, @scottmarlow ?

**Comment by TomasHofman** [comment]
What I mean is doing it this way: https://github.com/TomasHofman/el-ri/commit/a1642a3870230552cb5d14f1b922989f845fdfac

**Comment by TomasHofman** [comment]
I opened a PR so it's easier to comment on it: https://github.com/jboss/jboss-jakarta-el-api_spec/pull/11

**Comment by scottmarlow** [comment]
> @bstansberry as you mention differences between `class.getResourceAsStream(META-INF/services/xxxx)` and `ServiceLoader.load()`, I noticed one problem it introduces into testing.
> 
> This PR contains a test case which I've been unable to port to the 4.0.x branch due to the fact that the 4.0.x branch contains `module-info.java` file (making it a JPMS named module). In that environment, `ServiceLoader.load()` refuses to load my sample service class unless the service interface is listed in the `module-info.java`. I tried to add separate `module-info.java` to test resources dir, that would be used for tests instead of the real one, but I can't make that work.
> 
> So now I think if it wouldn't be better to keep using the original `class.getResourceAsStream(META-INF/services/xxxx)` way, and just sanitize what is read from the file.
> 
> WDYT @aogburn, @scottmarlow ?

Could you backport https://github.com/jboss/jboss-jakarta-el-api_spec/pull/11 to the 3.0.x branch?  I agree that is a safer change since it uses the original class.getResourceAsStream(META-INF/services/xxxx) way.

**Comment by TomasHofman** [comment]
@scottmarlow yes, I will do it tomorrow morning.

**Comment by TomasHofman** [comment]
It's here: https://github.com/jboss/jboss-jakarta-el-api_spec/pull/12

**Pull request closed without merging**
